# Generated by Django 6.0.1 on 2026-01-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroles',
            options={},
        ),
    ]
