# Generated by Django 6.0.1 on 2026-01-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_userroles_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
