# Generated by Django 6.0.3 on 2026-03-15 10:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.TextField(blank=True, null=True)),
                ('action_type', models.CharField(max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_id', models.TextField(blank=True, null=True)),
                ('resource_name', models.TextField(blank=True, null=True)),
                ('tenant_id', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.TextField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
