# Generated by Django 6.0.1 on 2026-01-14 13:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.TextField(unique=True)),
                ('hostname', models.TextField(blank=True, null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('architecture', models.TextField(blank=True, null=True)),
                ('agent_version', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('tenant_id', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agents',
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='agents_tenant__fad503_idx'), models.Index(fields=['agent_id'], name='agents_agent_i_cdfbf2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.TextField()),
                ('name', models.TextField()),
                ('resource_id', models.TextField()),
                ('resource_type', models.TextField()),
                ('provider', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('environment', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('lifecycle_state', models.TextField(blank=True, null=True)),
                ('health_status', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assets',
                'indexes': [models.Index(fields=['tenant_id', 'resource_type'], name='assets_tenant__5bdea3_idx'), models.Index(fields=['tenant_id', 'environment'], name='assets_tenant__1aeabf_idx'), models.Index(fields=['resource_id'], name='assets_resourc_57922f_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'resource_id'), name='unique_tenant_resource')],
            },
        ),
        migrations.CreateModel(
            name='AssetCompliance',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.TextField()),
                ('compliance_id', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_compliance',
                'indexes': [models.Index(fields=['asset_id'], name='asset_compl_asset_i_afd702_idx'), models.Index(fields=['compliance_id'], name='asset_compl_complia_bd7890_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset_id', 'compliance_id'), name='unique_asset_compliance')],
            },
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.TextField()),
                ('tag_key', models.TextField()),
                ('tag_value', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_tags',
                'indexes': [models.Index(fields=['asset_id', 'tag_key'], name='asset_tags_asset_i_52ca7d_idx'), models.Index(fields=['tag_key', 'tag_value'], name='asset_tags_tag_key_e58f79_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset_id', 'tag_key'), name='unique_asset_tag_key')],
            },
        ),
        migrations.CreateModel(
            name='AssetThreats',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.TextField()),
                ('threat_id', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_threats',
                'indexes': [models.Index(fields=['asset_id'], name='asset_threa_asset_i_3a0217_idx'), models.Index(fields=['threat_id'], name='asset_threa_threat__c370b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset_id', 'threat_id'), name='unique_asset_threat')],
            },
        ),
    ]
