# Generated by Django 6.0.1 on 2026-01-14 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0001_initial'),
        ('tenant_management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetThreat',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threat_id', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_threats',
            },
        ),
        migrations.RemoveIndex(
            model_name='assetthreats',
            name='asset_threa_asset_i_3a0217_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetthreats',
            name='asset_threa_threat__c370b9_idx',
        ),
        migrations.RemoveConstraint(
            model_name='assetthreats',
            name='unique_asset_threat',
        ),
        migrations.DeleteModel(
            name='AssetThreats',
        ),
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_tenant_resource',
        ),
        migrations.RemoveConstraint(
            model_name='assetcompliance',
            name='unique_asset_compliance',
        ),
        migrations.RemoveConstraint(
            model_name='assettag',
            name='unique_asset_tag_key',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='agents_tenant__fad503_idx',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='assets_tenant__5bdea3_idx',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='assets_tenant__1aeabf_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetcompliance',
            name='asset_compl_asset_i_afd702_idx',
        ),
        migrations.RemoveIndex(
            model_name='assettag',
            name='asset_tags_asset_i_52ca7d_idx',
        ),
        migrations.AddField(
            model_name='agent',
            name='tenant',
            field=models.ForeignKey(default='6397b96e-9c28-4796-a4bf-8a2e8d260ebb', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='tenant_management.tenants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(default='6397b96e-9c28-4796-a4bf-8a2e8d260ebb', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tenant_management.tenants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcompliance',
            name='asset',
            field=models.ForeignKey(default='6397b96e-9c28-4796-a4bf-8a2e8d260ebb', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_links', to='assets_management.asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assettag',
            name='asset',
            field=models.ForeignKey(default='6397b96e-9c28-4796-a4bf-8a2e8d260ebb', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='assets_management.asset'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['tenant', 'status'], name='agents_tenant__fad503_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'resource_type'], name='assets_tenant__5bdea3_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'environment'], name='assets_tenant__1aeabf_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcompliance',
            index=models.Index(fields=['asset'], name='asset_compl_asset_i_afd702_idx'),
        ),
        migrations.AddIndex(
            model_name='assettag',
            index=models.Index(fields=['asset', 'tag_key'], name='asset_tags_asset_i_52ca7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('tenant', 'resource_id'), name='unique_tenant_resource'),
        ),
        migrations.AddConstraint(
            model_name='assetcompliance',
            constraint=models.UniqueConstraint(fields=('asset', 'compliance_id'), name='unique_asset_compliance'),
        ),
        migrations.AddConstraint(
            model_name='assettag',
            constraint=models.UniqueConstraint(fields=('asset', 'tag_key'), name='unique_asset_tag_key'),
        ),
        migrations.AddField(
            model_name='assetthreat',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_links', to='assets_management.asset'),
        ),
        migrations.RemoveField(
            model_name='agent',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='assetcompliance',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='assettag',
            name='asset_id',
        ),
        migrations.AddIndex(
            model_name='assetthreat',
            index=models.Index(fields=['asset'], name='asset_threa_asset_i_3a0217_idx'),
        ),
        migrations.AddIndex(
            model_name='assetthreat',
            index=models.Index(fields=['threat_id'], name='asset_threa_threat__c370b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetthreat',
            constraint=models.UniqueConstraint(fields=('asset', 'threat_id'), name='unique_asset_threat'),
        ),
    ]
