# Generated by Django 6.0.3 on 2026-03-15 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_management', '0001_initial'),
        ('user_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantusers',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_auth.roles'),
        ),
        migrations.AddField(
            model_name='tenantusers',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenant_management.tenants'),
        ),
        migrations.AddField(
            model_name='tenantusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tenants',
            index=models.Index(fields=['name'], name='tenants_name_bc4541_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantusers',
            index=models.Index(fields=['tenant'], name='tenant_user_tenant__192555_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantusers',
            index=models.Index(fields=['user'], name='tenant_user_user_id_f93ec7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantusers',
            unique_together={('tenant', 'user')},
        ),
    ]
